import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";

import {
  discoverProxy,
  isReachable,
  normalizeProxyUrl,
  parseMixedPort,
  parseWindowsProxyServer,
  probeTcp,
  readClashMixedPort,
  readEnvProxy,
  stripQuotes,
} from "../lib/detect.js";

/** A path that never exists, so clash detection stays hermetic in tests. */
const NO_CLASH_FILES = { files: [path.join(os.tmpdir(), "dsh-wfp-absent-config.yaml")] };

test("normalizeProxyUrl accepts http(s) and the host:port shorthand", () => {
  assert.equal(normalizeProxyUrl("127.0.0.1:7897"), "http://127.0.0.1:7897");
  assert.equal(normalizeProxyUrl("http://127.0.0.1:7897"), "http://127.0.0.1:7897");
  assert.equal(normalizeProxyUrl("https://proxy.example:8443"), "https://proxy.example:8443");
  assert.equal(normalizeProxyUrl("  http://127.0.0.1:7890  "), "http://127.0.0.1:7890");
});

test("normalizeProxyUrl rejects empty, non-string and non-http schemes", () => {
  assert.equal(normalizeProxyUrl(""), undefined);
  assert.equal(normalizeProxyUrl("   "), undefined);
  assert.equal(normalizeProxyUrl(7897), undefined);
  assert.equal(normalizeProxyUrl("socks5://127.0.0.1:1080"), undefined);
  assert.equal(normalizeProxyUrl("http://"), undefined);
});

test("stripQuotes removes one pair of surrounding quotes", () => {
  assert.equal(stripQuotes('"7897"'), "7897");
  assert.equal(stripQuotes("'7897'"), "7897");
  assert.equal(stripQuotes("7897"), "7897");
  assert.equal(stripQuotes('"'), '"');
});

test("parseMixedPort reads the mixed listener only", () => {
  assert.equal(parseMixedPort("# Generated by Clash Verge\nmixed-port: 7897\n"), 7897);
  assert.equal(parseMixedPort('mixed-port: "7897"\n'), 7897);
  assert.equal(parseMixedPort("verge_mixed_port: 7890\n"), 7890);
  assert.equal(parseMixedPort("socks-port: 7898\n"), undefined);
  assert.equal(parseMixedPort("# mixed-port: 7897\n"), undefined);
  assert.equal(parseMixedPort("mixed-port: 0\n"), undefined);
  assert.equal(parseMixedPort("mixed-port: not-a-port\n"), undefined);
  assert.equal(parseMixedPort(undefined), undefined);
});

test("readClashMixedPort returns the port and the file that supplied it", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-"));
  try {
    const file = path.join(dir, "config.yaml");
    fs.writeFileSync(file, "ipv6: true\nmixed-port: 7897\n", "utf8");
    assert.deepEqual(readClashMixedPort({ files: [file] }), { port: 7897, file });
    assert.equal(readClashMixedPort({ files: [path.join(dir, "missing.yaml")] }), undefined);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("parseWindowsProxyServer handles both WinINET notations", () => {
  assert.deepEqual(parseWindowsProxyServer("127.0.0.1:7897"), { url: "http://127.0.0.1:7897", source: "windows-registry" });
  const perScheme = parseWindowsProxyServer("http=127.0.0.1:7890;https=127.0.0.1:7897");
  assert.equal(perScheme.url, "http://127.0.0.1:7897");
  assert.equal(parseWindowsProxyServer(""), undefined);
  assert.equal(parseWindowsProxyServer("; ;"), undefined);
});

test("readEnvProxy ranks the plugin variable first", () => {
  assert.equal(readEnvProxy({ HTTPS_PROXY: "http://127.0.0.1:7897" }).source, "env:HTTPS_PROXY");
  assert.equal(readEnvProxy({ DSH_WEB_FETCH_PROXY: "http://127.0.0.1:1", HTTPS_PROXY: "http://127.0.0.1:2" }).url, "http://127.0.0.1:1");
  assert.equal(readEnvProxy({ all_proxy: "socks5://127.0.0.1:1080" }), undefined);
  assert.equal(readEnvProxy({}), undefined);
});

test("probeTcp and isReachable follow a real listener", async () => {
  const server = net.createServer();
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const port = server.address().port;
  try {
    assert.equal(await probeTcp("127.0.0.1", port, 1000), true);
    assert.equal(await isReachable("http://127.0.0.1:" + port + "/", 1000), true);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
  assert.equal(await probeTcp("127.0.0.1", port, 400), false);
  assert.equal(await isReachable("not a url", 400), false);
});

test("discoverProxy honours an explicit config value", async () => {
  const hit = await discoverProxy({ explicit: "127.0.0.1:7897", reachable: async () => true });
  assert.deepEqual(hit, { url: "http://127.0.0.1:7897", source: "config" });
  assert.equal(await discoverProxy({ explicit: "127.0.0.1:7897", reachable: async () => false }), undefined);
  assert.equal(await discoverProxy({ explicit: "socks5://127.0.0.1:1080", reachable: async () => true }), undefined);
});

test("discoverProxy falls through environment, clash config and the port probe", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dsh-wfp-"));
  try {
    const file = path.join(dir, "config.yaml");
    fs.writeFileSync(file, "mixed-port: 7899\n", "utf8");

    const fromEnv = await discoverProxy({
      explicit: "auto",
      env: { HTTPS_PROXY: "http://127.0.0.1:7897" },
      clashOptions: NO_CLASH_FILES,
      reachable: async (url) => url === "http://127.0.0.1:7897",
    });
    assert.equal(fromEnv.source, "env:HTTPS_PROXY");

    const fromClash = await discoverProxy({
      explicit: "auto",
      env: {},
      clashOptions: { files: [file] },
      reachable: async (url) => url === "http://127.0.0.1:7899",
    });
    assert.equal(fromClash.url, "http://127.0.0.1:7899");
    assert.ok(fromClash.source.startsWith("clash-config:"));

    const fromProbe = await discoverProxy({
      explicit: "auto",
      env: {},
      clashOptions: NO_CLASH_FILES,
      ports: [1234, 7897],
      reachable: async (url) => url === "http://127.0.0.1:7897",
    });
    assert.deepEqual(fromProbe, { url: "http://127.0.0.1:7897", source: "port-probe:7897" });

    const nothing = await discoverProxy({
      explicit: "auto",
      env: {},
      clashOptions: NO_CLASH_FILES,
      ports: [1234],
      reachable: async () => false,
    });
    assert.equal(nothing, undefined);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
